In [2]:
import numpy
numpy.__version__


'1.24.3'

In [3]:
import numpy as np

In [4]:
np?

In [6]:
result = 0
for i in range(10):
    result +=i
    print(result)

0
1
3
6
10
15
21
28
36
45


In [8]:
#A PYTHON LIST IS MORE THAN JUST A LIST
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
print(type(L))
print(type(L[0]))

<class 'list'>
<class 'int'>


In [20]:
L2 = [str(D) for D in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [21]:
print(type(L2))
print(type(L2[0]))

<class 'list'>
<class 'str'>


In [22]:
L3 = [True,'2',3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [31]:
import array
L = list(range(10))
A = array.array('i',L)
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [32]:
#CREATING ARRAY FROM PYTHON LIST
np.array([1,2,3,4,5,6,6])

array([1, 2, 3, 4, 5, 6, 6])

In [33]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [34]:
np.array([1,2,3,4,5,6,7], dtype='float32')

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)