In [8]:
import numpy
numpy.__version__


'1.24.3'

In [9]:
import numpy as np

In [10]:
np?

In [11]:
result = 0
for i in range(10):
    result +=i
    print(result)

0
1
3
6
10
15
21
28
36
45


In [12]:
#A PYTHON LIST IS MORE THAN JUST A LIST
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
print(type(L))
print(type(L[0]))

<class 'list'>
<class 'int'>


In [14]:
L2 = [str(D) for D in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
print(type(L2))
print(type(L2[0]))

<class 'list'>
<class 'str'>


In [16]:
L3 = [True,'2',3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [17]:
import array
L = list(range(10))
A = array.array('i',L)
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [18]:
#CREATING ARRAY FROM PYTHON LIST
np.array([1,2,3,4,5,6,6])

array([1, 2, 3, 4, 5, 6, 6])

In [19]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [20]:
np.array([1,2,3,4,5,6,7], dtype='float32')

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [21]:
#THE BASIS OF NumPy Arrays
import numpy as np
np.random.seed(0) #seed for reproductivity

x1 = np.random.randint(10, size=6) #One dimentional array
x2 = np.random.randint(10, size=(3,4)) #Two dimensional array
x3 = np.random.randint(10, size=(3,4,5)) #Three dimensional array


In [22]:
print("x3 ndim: ", x3.ndim)
print("x2 ndim: ", x2.ndim)
print("x1 ndim: ", x1.ndim)

x3 ndim:  3
x2 ndim:  2
x1 ndim:  1


In [23]:
print("x3 ndim: ", x3.ndim)
print("x3 ndim: ", x3.shape)
print("x3 ndim: ", x3.size)

x3 ndim:  3
x3 ndim:  (3, 4, 5)
x3 ndim:  60


In [24]:
# mport numpy as np

# # Set the seed for reproducibility
# np.random.seed(0)

# # Generate a random array
# random_array = np.random.rand(3)

# print(random_array)
# Output:

# csharp
# Copy code
# [0.5488135  0.71518937 0.60276338]
# If you run this code multiple times, you'll get the same output every time because the seed has been set to 0. Without setting the seed, the output would vary with each execution.

# Setting the seed is particularly useful when you need to:

# Compare results from different algorithms under the same random conditions.
# Debug or verify the behavior of code that involves randomness.
# Ensure consistent results in tutorials, documentation, or educational materials.

In [25]:
print("x1 dtype: ", x1.dtype)
print("x1 itemsize: ", x1.itemsize, "bytes")
print("x2 itemsize: ", x2.itemsize, "bytes")
print("x3 itemsize: ", x3.itemsize, "bytes")
print("nbytes",x3.nbytes)
print("size", x3.size)

x1 dtype:  int32
x1 itemsize:  4 bytes
x2 itemsize:  4 bytes
x3 itemsize:  4 bytes
nbytes 240
size 60


In [26]:
x1

array([5, 0, 3, 3, 7, 9])

In [27]:
x1[0]

5

In [28]:
x1[4]

7

In [29]:
#The index from the end of the array
x1[-1]


9

In [30]:
x1[-2]

7

In [31]:
#In a multi-dimensional array elements can be accessed using a comma-separated tuple of indices
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [32]:
x2[0,0]

3

In [33]:
x2[0,3]

4

In [34]:
x2[2,-1]

7

In [35]:
x2[2,0]

1

In [36]:
#Value modification
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [37]:
x1

array([5, 0, 3, 3, 7, 9])

In [38]:
x1[0] = 2.14
x1

array([2, 0, 3, 3, 7, 9])

In [39]:
#Array Slicing: Accessing Subarrays
#    X[START:STOP:STEP]
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
x[:5] #first five elements

array([0, 1, 2, 3, 4])

In [41]:
x[5:] # elements after five

array([5, 6, 7, 8, 9])

In [42]:
x[4:7]

array([4, 5, 6])

In [43]:
x[::2] #every other elements

array([0, 2, 4, 6, 8])

In [44]:
x[1::2]  #every other elements starting from index 1

array([1, 3, 5, 7, 9])

In [45]:
x[::-1] #All elements are reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [46]:
x[5::-2] #reversed every other from index 5

array([5, 3, 1])

In [47]:
#MULT DIMENSIONAL ARRAT SLICING 
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [48]:
x2[:2,:3] #two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [49]:
x2[:3,::3] #ALL ROWS AND ALL OTHER COLUMSN

array([[12,  4],
       [ 7,  8],
       [ 1,  7]])

In [50]:
#subarray can also be reversed together
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [51]:
x2[::-1, ::-1] #all rows and columns are reversed

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [52]:
#accessing array rows and columns of x2
print(x2[:,0])

[12  7  1]


In [53]:
print(x2[0,:]) #first row of x2

[12  5  2  4]


In [54]:
print(x2[0])

[12  5  2  4]


In [55]:
# SUBARRAYS AS NO-COPY VIEWS
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [56]:
# let's extract 2 x 2 subaary from this 
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [57]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [58]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [59]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [60]:
x2_sub_copy[0,0] = 212
print( x2_sub_copy,"\n\n\n")
print(x2)

[[212   5]
 [  7   6]] 



[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [61]:
#Arraying reshaping 
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
xx = np.array([1,2,3])
#row vector via reshape
xx.reshape((1,3))

array([[1, 2, 3]])

In [63]:
#Array concatenation of arrays
q = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([q,y])

array([1, 2, 3, 3, 2, 1])

In [66]:
z = [99,99,99]
s = [2,3,4,44,44]
print(np.concatenate([z,s]))


[99 99 99  2  3  4 44 44]


In [67]:
grid = np.array([[1,2,3],
                [4,5,6]])

In [68]:
print(np.concatenate([grid,grid]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [69]:
print(np.concatenate([grid,grid],axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [74]:
#splitting of arrays 
x = [1,2,3,4,5,6,7,8,99]
x1,x2,x3 = np.split(x,[2,1])
print(x1,x2,x3)

[1 2] [] [ 2  3  4  5  6  7  8 99]


In [75]:
#EXAMPLE

In [86]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output
values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.11111111, 0.14285714, 0.14285714, 0.125     , 0.125     ])

In [87]:
big_array = np.random.randint(1,10, size=100)
%timeit compute_reciprocals(big_array)

264 µs ± 9.49 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [90]:
b = 12 + 54
%timeit 12 + 54

15 ns ± 2.01 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [93]:
arr = np.random.randint(3,9,size = 5)
print(arr)

[7 4 8 4 3]


In [94]:
print(1/arr)

[0.14285714 0.25       0.125      0.25       0.33333333]


In [100]:
x = np.arange(4)
print("x     =",x)
print("x + 5 =",x +5)
print("x - 5 =", x-5)
print("x * 5 =", x*5)
print("x / 5 =",x/5)
print("x //5 =",x//5)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 5 = [ 0  5 10 15]
x / 5 = [0.  0.2 0.4 0.6]
x //5 = [0 0 0 0]


In [103]:
result =np.add(x,3)
print(result)

[3 4 5 6]


In [104]:
# np.add
# np.substract
# np.negative
# np.multiply
# np.divide
# np.floor_divide
# np.power
# np.mod

In [105]:
#Absolute value
x = np.array([-2,-1,0,1,2])
print(abs(x))

[2 1 0 1 2]


In [107]:
#Trigonometric functions
theta = np.linspace(0,np.pi,3)
print(theta)

[0.         1.57079633 3.14159265]


In [109]:
print(theta)
print("Sin",np.sin(theta))
print("Cos",np.cos(theta))
print("Tan",np.tan(theta))

[0.         1.57079633 3.14159265]
Sin [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cos [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Tan [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [110]:
from scipy import special
x = [1,]